### ISSUE TITLE
building nuke to hydra usd pxrConfig error question

### ISSUE THREAD

**Issue by lucienfostier** [nrusch/nuke-to-hydra#11] opened 2020-05-14 05:52 UTC
Hello Nathan,

I've been trying to build the project using a pre built binaries from Nvidia for USD 20.02 but I'm getting the following error:

```
CMake Error at CMakeLists.txt:13 (include):
  include could not find load file:

    pxrConfig


-- USD_ROOT: /home/lucienf/Downloads/usd-20.02-linux64_py27_release
-- Configuring incomplete, errors occurred!
See also "/home/lucienf/dev/git/nuke-to-hydra/CMakeFiles/CMakeOutput.log".

```

I've checked the log file but nothing is helpful.
I can see the file `pxrConfig.cmake` at the USD root folder I specified.
Any help would be appreciated.
Thanks
Lucien

**Comment by nrusch** [comment] 2020-05-14 06:18
Hi Lucien,

I think I overlooked some of the specifics of my own build environment and made some inflexible assumptions. As a test, can you try passing `-D CMAKE_MODULE_PATH=<YOUR_USD_ROOT>` (as well as `-D USD_ROOT=<YOUR_USD_ROOT>`)?

I eventually want to move away from using `pxrConfig`, since it doesn't work particularly well with some USD build configurations, but assuming the issue here is what I think it is, this should be a fairly easy one to fix in the meantime.

**Comment by lucienfostier** [comment] 2020-05-14 16:24
Hi Nathan,

yes that did bring me further. At this point, I think I should try to build USD from source as I'm getting error about missing `tbb`.
I guess your project is setup to be compile as part of USD itself?

I will try a few things and then let you know.
Thanks for your fast answer.

**Comment by nrusch** [comment] 2020-05-14 17:23
This project does not need to be compiled as part of USD itself. However, the issue with `pxrConfig` is that it contains hard-coded paths to the dependencies that USD was built with (including things like TBB). That's probably why you're getting errors, and is why I would like to move away from using it.

I should be able to download the precompiled libs from Nvidia later and start experimenting with building against them. I'm not familiar with how they are laid out or linked, but you will almost definitely still need headers for some of the USD dependencies, since they are included by various pxr headers.

**Comment by nrusch** [comment] 2020-05-14 20:20
OK, it looks like the Nvidia builds ship with TBB and Boost headers and libraries, so I think it's time for me to update the build to support specifying separate locations for those installs (I've just been using `pxrConfig` because it was really easy to get off the ground). I don't anticipate the changes taking too long.

**Comment by nrusch** [comment] 2020-05-15 06:10
OK, I've updated the build to allow more granular specification of the USD dependencies, and I've confirmed that it builds against the Nvidia USD builds. I'm still using GCC 4.8, while they're using something newer, so I haven't actually been able to do a runtime test yet, but all of the library linkage appears to be correct.

Building against the Nvidia distro should be as simple as:

```
cmake \
-D CMAKE_INSTALL_PREFIX=<YOUR_DEST_PREFIX> \
-D Nuke_ROOT=<YOUR_NUKE_ROOT>
-D CMAKE_PREFIX_PATH=/home/lucienf/Downloads/usd-20.02-linux64_py27_release \
<PATH_TO_SOURCE>
```

Let me know if that helps.

**Comment by lucienfostier** [comment] 2020-05-15 07:11
Yep that worked to compile!

I have to look into it a bit more in details because I’m having undefined symbols problem at runtime.
I also need to download the arnold delegate.
Still a few steps before I can play but that’s already really helpful, thanks a lot!

I’ll keep you posted with my progress

**Comment by lucienfostier** [comment] 2020-05-16 05:46
So I rebuild USD from scratch using 20.02.
`
I recompile nuke to hydra with the new compile USD and then I set the `LD_LIBRARY_PATH` but I get the following undefined symbol at runtime in nuke:

```/home/lucienf/dev/git/nuke-to-hydra/build/plugins/../lib/libHdNuke.so: undefined symbol: _ZN32pxrInternal_v0_20__pxrReserved__15HdSceneDelegate23GetExtComputationKernelERKNS_7SdfPathE```

which is the following symbol:

`pxrInternal_v0_20__pxrReserved__::HdSceneDelegate::GetExtComputationKernel(pxrInternal_v0_20__pxrReserved__::SdfPath const&)`

I did check my symbol on the compile lib:

```nm -C ~/apps/USD/lib/libhd.so  | grep -i getExtComputationKernel
000000000010e380 T pxrInternal_v0_20__pxrReserved__::HdSceneDelegate::GetExtComputationKernel(pxrInternal_v0_20__pxrReserved__::SdfPath const&)```

I haven't compile the arnold render delegate yet but I don't think that would explain my undefined symbol...
Not sure what's wrong here :(

**Comment by nrusch** [comment] 2020-05-16 06:19
Hmm... That looks like your HdNuke lib isn't properly linked to the USD libraries specified in the build, which doesn't make a lot of sense if the build completed successfully. Some additional questions:

- When you say you're setting `LD_LIBRARY_PATH`, what are you setting it to? The `lib` dir of your USD build?
    - The HdNuke build should set the RPATH of the libs and plugins to include the path to the USD library dirs, so `LD_LIBRARY_PATH` shouldn't be necessary... did you actually install the project as part of your build (i.e. `make install`)? That's when CMake sets the RPATHs up.
- When are you getting that symbol error? In other words, what are you trying to do when you trigger it (creating a specific node type, etc.)?
- Do you have anything else in your Nuke environment that might be causing a different set of USD libs to be loaded, which might perhaps use a different symbol namespace?
    - Other USD-related plugins, code in and `init.py`/`menu.py` that's importing pxr Python bindings...
- What versions of Nuke, GCC, and CMake are you using?
- What do you get when you run `readelf -d /path/to/libHdNuke.so | grep NEEDED`?

**Comment by nrusch** [comment] 2020-05-16 06:49
Oh, can you also check the output of `readelf -d /path/to/libHdNuke.so | grep RPATH`?

**Comment by lucienfostier** [comment] 2020-05-17 05:44
Hey Nathan,

Ok I took another look using `LD_DEBUG` and indeed I was using the first lib I tried to compile again ( the NVIDIA pre compiles binaries ).

After cleaning the cmake build caching, I was able to recompile the project using my own build of USD.

Now I can create the nodes and there is no more error.
I guess I need to learn a bit more about cmake as I'm using Scons at work and that's an annoying issue to be stuck with.

Thanks for all your help!

Now onto compiling the arnold delegate...I guess you used:

https://github.com/Autodesk/arnold-usd

Cheers

**Comment by nrusch** [comment] 2020-05-17 17:09
Cool, glad to hear you got it sorted out. I'm going to close this issue, but feel free to open a new one if you have any other issues or questions.

**Closed by nrusch** 2020-05-17 17:09 UTC

**Comment by lucienfostier** [comment] 2020-05-19 06:14
Hey Nathan,

just to let you know that I was able to render my first images with nuke to hydra!

I think the AA samples are pretty high because it locked my machine for 5 minutes at first...

![second_image](https://user-images.githubusercontent.com/770272/82291095-2d586f00-995d-11ea-8a0d-06f4ec2456a6.png)

What is your plan to work on the issues opened like texturing and materials? Are you looking for contributions?

Thanks a lot!

**Comment by nrusch** [comment] 2020-05-19 06:34
Good to hear! I think the Arnold delegate defaults to 10 AA samples with progressive rendering enabled, so it'll actually render the frame 3 or 4 times (with the last one at full sampling), which ends up taking a while. Unfortunately, there's no way to do progressive updates in the Nuke viewer during an engine call, so it basically just seems like a really slow render. You can change the sampling settings and disable progressive rendering using the delegate settings knobs on the HydraRender node though.

In terms of texturing and materials, I have a rough plan to implement a generalized Sdr shader op and material network translation, which should open the door to fairly flexible material authoring. However, the "Iops-as-textures" problem is quite complex in terms of trying to generalize it for arbitrary renderers... So far the texture arena idea is the only thing that I think would really cover all the bases, but it's something I haven't started actively working on yet. I would certainly be open to contributions, but it's a big enough problem that I'm certainly not expecting anyone to just casually drop it off as a PR. :)

I am currently close to finishing a USD stage op to allow side-loading of stages into the render index without passing them through Nuke's 3D system, and I would still like to add some proper viewer handles for the Hydra light ops.

There are also some other irons in the fire with other fairly motivated parties that I can't talk about just yet, but which will hopefully be revealed before too long.
